version: "3.9"

services:
  backend:
    image: morrmaks/lumi-backend:latest
    container_name: lumi-backend
    env_file:
      - /root/lumi-backend-config/.env
    networks:
      - lumi-net
    ports:
      - "4000:4000"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/api/health"]
      interval: 10s
      retries: 5

  frontend:
    image: morrmaks/lumi-frontend:latest
    container_name: lumi-frontend
    networks:
      - lumi-net
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: always

networks:
  lumi-net:
    external: true
