services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        BASE_API: /api
        STATIC: /static/
        YA_SUGGEST_API_KEY: ${YA_SUGGEST_API_KEY}
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: on-failure

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
        PORT: 4000
        DB_URL: ${DB_URL}
        JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
        JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
        SMTP_HOST: ${SMTP_HOST}
        SMTP_PORT: ${SMTP_PORT}
        SMTP_USER: ${SMTP_USER}
        SMTP_PASSWORD: ${SMTP_PASSWORD}
        API_URL: ${API_URL}
        CLIENT_URL: ${CLIENT_URL}
        YOO_SHOP_ID: ${YOO_SHOP_ID}
        YOO_SECRET_KEY: ${YOO_SECRET_KEY}
    env_file:
      - ./backend/.env
    expose:
      - "4000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/api/health"]
      interval: 10s
      retries: 5
    restart: on-failure
